baseURL = "https://shencoder.netlify.com/"
languageCode = "en-us"
title = "Sen Coder"
theme = "Mainroad"
paginate = "5"
disqusShortname = "shencoder"
googleAnalytics = "UA-155263469-2" # Enable Google Analytics by entering your tracking id

[Author] # Used in authorbox
  name = "Sen Coder"
  bio = "Sen Coder is a Vlogger."
  avatar = "img/profile-picture.webp"

[Params]
  subtitle = "Learn Programming in Simplest Way" # Subtitle of your site. Used in site header
  description = "Learn Programming in Simplest Way" # Site description. Used in meta description
  #copyright = "John Doe" # copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  #mainSections = ["post", "blog", "news"] # specify section pages to show on home page and the "Recent articles" widget
  #dateformat = "2006-01-02" # change the format of dates
  #mathjax = true # Enable MathJax
  #mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  #highlightColor = "#e22d30" # Override highlight color
  customCSS = ["css/main.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 7 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
   facebook = "shencoder"
   twitter = "shencoder"
   email = "sen.coder9901@gmail.com"
   #instagram = "username"
   #github = "sen-coder"
