---
label: Default
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: thumbnail
  label: thumbnail
- type: boolean
  name: comments
  label: comments
- type: list
  name: tags
  label: tags
- type: list
  name: categories
  label: categories
