---
label: Default
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: thumbnail
  label: thumbnail
- type: boolean
  name: comments
  label: comments
- type: list
  name: tags
  label: tags
- type: list
  name: categories
  label: categories
pages:
- content/post/How to build a GraphQL with MongoDB and Ktor.md
- content/post/apollo-graphql-and-android.md
- content/post/create-a-graphql-with-mongodb-go.md
- content/post/create-a-login-and-register-tornadofx-with-mysql.md
- content/post/deploy-ktor-app-to-heroku.md
- content/post/how-to-insert-and-select-statements-in-room-database-android.md
- content/post/mvvm-and-live-data-android.md
- content/post/navigation-component-in-kotlin-android.md
